# Generated by Django 3.0.5 on 2020-07-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientdatamodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('weight', models.CharField(default='', max_length=40)),
                ('age', models.CharField(default='', max_length=40)),
                ('symptomps', models.CharField(default='', max_length=40)),
                ('doctor', models.CharField(default='', max_length=40)),
                ('file', models.FileField(upload_to='files/pdfs/')),
            ],
            options={
                'db_table': 'patientdata',
            },
        ),
    ]
