# Generated by Django 3.0.5 on 2020-07-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patienttreatmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('symptomps', models.CharField(default='', max_length=40)),
                ('treatment', models.CharField(default='', max_length=40)),
            ],
            options={
                'db_table': 'patienttreatment',
            },
        ),
    ]
