# Generated by Django 3.0.5 on 2020-07-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='storedatamodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregnancies', models.CharField(max_length=500)),
                ('Glucose', models.CharField(max_length=300)),
                ('BloodPressure', models.CharField(max_length=300)),
                ('SkinThickness', models.CharField(max_length=300)),
                ('Insulin', models.CharField(max_length=255)),
                ('BMI', models.CharField(max_length=255)),
                ('DiabetesPedigreeFunction', models.CharField(max_length=255)),
                ('Age', models.CharField(max_length=255)),
                ('Outcome', models.CharField(max_length=255)),
            ],
        ),
    ]
